['/Users/kurosuryou/kyoto-kurosuryo', '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python39.zip', '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9', '/opt/homebrew/Cellar/python@3.9/3.9.12/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload', '/Users/kurosuryou/Library/Python/3.9/lib/python/site-packages', '/opt/homebrew/lib/python3.9/site-packages', '/opt/homebrew/lib/python3.9/site-packages/certifi-2019.9.11-py3.9.egg', '/opt/homebrew/lib/python3.9/site-packages/chardet-3.0.4-py3.9.egg', '/opt/homebrew/lib/python3.9/site-packages/idna-2.8-py3.9.egg', '/opt/homebrew/lib/python3.9/site-packages/six-1.12.0-py3.9.egg', '/opt/homebrew/Cellar/pybind11/2.9.2/libexec/lib/python3.9/site-packages', '/opt/gurobi201/linux32/lib/python2.5', '/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx']
Traceback (most recent call last):
  File "/Users/kurosuryou/kyoto-kurosuryo/dt_for_cv.py", line 14, in <module>
    import dt_tools, read_datasets
  File "/Users/kurosuryou/kyoto-kurosuryo/dt_tools.py", line 14, in <module>
    import cplex
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/__init__.py", line 44, in <module>
    from .aborter import Aborter
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/aborter.py", line 13, in <module>
    from ._internal import _procedural as _proc
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/__init__.py", line 20, in <module>
    from . import _list_array_utils
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/_list_array_utils.py", line 14, in <module>
    from . import _pycplex as CPX
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/_pycplex.py", line 13, in <module>
    from . import _pycplex_platform
  File "/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/_pycplex_platform.py", line 26, in <module>
    from cplex._internal.py39_cplex2210 import *
ImportError: dlopen(/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/py39_cplex2210.so, 0x0002): tried: '/Applications/CPLEX_Studio221/cplex/python/3.9/x86-64_osx/cplex/_internal/py39_cplex2210.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e'))
